name: cryptoMgmt
run-name: ${{github.actor}} is running Github Actions...
on: [pull_request, push]
jobs:
  run-jest:
    runs-on: ubuntu-latest
    environment: cryptoMgmt
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - name: run tests
        run: npm test
        env:
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          BSCSCAN_API_KEY: ${{secrets.BSCSCAN_API_KEY}}
          MONGO_URI: ${{secrets.MONGO_URI}}
          MONGO_TEST_URI: ${{secrets.MONGO_TEST_URI}}
